image: pnavaro/jupyter

pages:
  stage: deploy
  script:
    - pip install --user -U jupyter-book
    - jupyter-book build .
    - mv _build/html public
  artifacts:
    paths:
      - public
  tags:
    - small
