image: pnavaro/selalib

pages:
  stage: deploy
  script:
    - pip3 install --user jupyter-book
    - jupyter-book build .
    - mv _build/html public
  artifacts:
    paths:
      - public
  tags:
    - small
